### ISSUE TITLE
Using a different inference engine with ChatUI or WebUI

### ISSUE THREAD

**Issue by kinchahoy** [av/harbor#15]
For a few reasons, I need to use a non-llama.cpp based inference engine. I couldn't figure out how to get a working UI using Harbor, VLLM and ChatUI or WebUI (other than just VLLM serve by itself). Could you share a few more examples / demos that don't depend on Ollama / Llama.cpp?

**Comment by av** [comment]
Hi, thanks for trying out Harbor!

To permanently switch from  `ollama` to `vllm`:
```bash
harbor defaults rm ollama
harbor defaults add vllm
```

I've mentioned this in the [high-level user guide](https://github.com/av/harbor/wiki/1.-Harbor-User-Guide#default-services)

This will come with a few notable caveats:
- Runs one model at a time, can't swap dynamically, Harbor doesn't yet support running multiple instances of the same service, so to change the LLM you'd need to `down`, reconfigure and then `up` again
- There are no ARM docker image builds, if you're on MacOS
- Integrated with fewer services out of the box

**Comment by av** [comment]
Just released `harbor profile` functionality in [v0.1.21](https://github.com/av/harbor/releases/tag/v0.1.21), could be helpful in this context

**Comment by av** [comment]
Feel free to reopen if any more follow-ups are needed
