### ISSUE TITLE
Support for KTransformers

### ISSUE THREAD

**Issue by maeyounes** [av/harbor#18]
Hello,

Thanks for putting the work into this amazing project. I really enjoy its flexibility.

I wonder if there are plans to add support for the backend KTransformers https://github.com/kvcache-ai/ktransformers as it probably the best framework to serve mixture of expert type models such as Mixtral and DeepSeek-Coder models locally. 

Best regards,
MY

**Comment by av** [comment]
Thanks for bringing it to my attention, I'm working on the integration now
