### ISSUE TITLE
Using a different Ollama URL?

### ISSUE THREAD

**Issue by zheroz00** [av/harbor#19]
Hey there. Great project, very handy.

I have ollama installed on my LLM server and its already integrated with a ton of other services. Is it possible to have harbor use the ollama service I already have installed, while still maintaining the rest of the integration?

Thanks

**Comment by av** [comment]
Yes, right now it's already possible to specify the custom cache location, to at least share the downloaded blobs:
```bash
harbor config get ollama.cache
harbor config set ollama.cache ~/path/to/cache
```

However, I agree that you might want to use a completely external Ollama instance. I've added a preliminary support in [v0.1.26](https://github.com/av/harbor/releases/tag/v0.1.26), please let me know if it works

**Comment by zheroz00** [comment]
@av This is great! Ty, So if I already have Ollama installed as a service at 10.10.10.158:11434, should I be able to run 'harbor config set ollama.internal_url http://10.10.10.158:11434' and it should use that by default? How does this affect the yaml files and the ollama containers they typically start up?
Sorry for all the questions. I find this project really interesting.

**Comment by av** [comment]
I assume that `10.10.10.158:11434` is ping-able from the host, what you want to use a version that is ping-able in the same way from Harbor containers.

One way to test that is:
```bash
# spin up some services
harbor up

# Enter webui container
harbor exec webui bash

# Try to find where your LAN addresses are
curl http://10.10.10.158:11434
```

`172.17.0.1` would be yout host's `localhost` on Linux, unfortunately I never tried to ping devices on LAN from within the containers (only the vice versa, haha), so don't know for sure if they'll be reachable

> How does this affect the yaml files and the ollama containers they typically start up?

I aimed to switch all the services to use that paremeterisable Ollama URL, if the address is reachable, they should be able to still access it

> When I restarted the containers it wipes out those additional endpoints. Is there a correct way to set additional endpoints via CLI?

Sorry for the inconvenience, that probably wasn't a pleasant discovery! That's an unfortunate drawback of the current setup, the bi-directional config binding doesn't work. WebUI recently switched to SQLite for config storage, which made it even more complicated, so, yes - Harbor will overwrite all the configuration items that can be modified by it on every start. I think there are ways around that, but they are quite complex compared to the outcome, so I dind't explore them yet.

One feature that might help are "additional" OpenAI API endpoints:
```
Usage: harbor openai <command>

Commands:
  harbor openai keys [ls|rm|add]   - Get/set the API Keys for the OpenAI-compatible APIs.
  harbor openai urls [ls|rm|add]   - Get/set the API URLs for the OpenAI-compatible APIs.
```
All of these will be appended to whatever other services in Harbor that WebUI connects to. 
- You have to "align" keys with URLs by index
- WebUI won't connect to OpenAI-compatible API without a key, so either plug in a stub, or setup the API to use an actual key auth

**Comment by av** [comment]
Closing the issue, please let me know how the tests go - we'll reopen if needed
