### ISSUE TITLE
Suggestion: Rename containers (ex: ollama -> harbor_ollama, searxng -> harbor_searxng)

### ISSUE THREAD

**Issue by alsoasnerd** [av/harbor#2]
I'm running an instance of searxng on my host, and the container name is the same as the harbor instance. To avoid incompatibilities, isn't better use an "harbor prefix"?

**Comment by av** [comment]
Thank you for the suggestion, current setup was chosen out of aesthetic + compatibility between container names and service handles that is useful in a few places.

I'll add a customizable prefix in the next release

**Comment by av** [comment]
Released in [v0.0.12](https://github.com/av/harbor/releases/tag/v0.0.12)

**Comment by alsoasnerd** [comment]
Good! Thanks for attention.
