### ISSUE TITLE
Permission issue with LibreChat Deployment

### ISSUE THREAD

**Issue by maeyounes** [av/harbor#20]
Hello,

I'm running into a permission issue when deploying LibreChat under Harbor. I get the following error when starting the container:
```
> LibreChat@v0.7.5-rc2 backend
> cross-env NODE_ENV=production node api/server/index.js

2024-09-17 11:37:21 info: [Optional] Redis not initialized. Note: Redis support is experimental.
2024-09-17 11:37:23 error: There was an uncaught error: EACCES: permission denied, open '/app/api/logs/meiliSync-2024-09-17.log'
```

Then the container stops and exits.

I tried reverting to an older image version than the latest one but I still get the same error.
I also tried setting the variables PUID and PGID to 1000.
None of this worked.

Deploying with the docker-compose file from the original LibreChat repository does not have this issue.

**Comment by av** [comment]
Sorry, you were so quick I didn't manage to provide the feedback in time!

FS permissions are a classic issue when mounting host volumes with docker. So, there's a built-in (underdocumented, though) util to fix:

```bash
harbor fixfs
```

It'll prompt you for the user password and will run as `root`, updating the permissions on folders of most of the services
