### ISSUE TITLE
NexaAI integration

### ISSUE THREAD

**Issue by av** [av/harbor#24]
Another interesting backend:
https://github.com/NexaAI/nexa-sdk?tab=readme-ov-file#docker-usage

**Comment by bhupesh-sf** [comment]
Love to see it here, today only I was planning to experiment with it and here I found it's already in the works. Thank you very much

**Comment by av** [comment]
Added in v0.2.5, unfortunately Nexa server isn't feature-complete yet, so it's only partial at this stage
