### ISSUE TITLE
macOS `sed` incompatibility in harbor.sh

### ISSUE THREAD

**Issue by montasaurus** [av/harbor#32]
When I first ran `./harbor.sh ln` on macOS, I got an error message:
```
sed: 1: ".env": invalid command code .
```

Looks like it was caused by a [difference in GNU sed and macOS sed](https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux).

I was able to get it running with:
```bash
brew install gnu-sed
PATH="$(brew --prefix gnu-sed)/libexec/gnubin:$PATH" ./harbor.sh link
```

**Comment by av** [comment]
Thank you for trying out Harbor!

Shell portability made me rethink initial design choices multiple time. I though I covered cases [like this](https://github.com/av/harbor/blob/main/harbor.sh#L776), but apparently not all of them yet.

I pushed a hotfix, it should be available via `harbor update --latest` or whenever next release goes live

**Comment by av** [comment]
Closing, [v0.1.32](https://github.com/av/harbor/releases/tag/v0.1.32) included a few other compatibility fixes for MacOS
