### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by alsoasnerd** [av/harbor#4]

**Comment by av** [comment]
Right now, it's `git pull` when you are in the harbor folder, we'll add more convenient way to do this along with the one-line installation script later

**Comment by av** [comment]
The latest version comes with a `harbor update` helper (no release tag yet), this is a stub until the mentioned functionality is in place

**Comment by av** [comment]
officially in [v0.0.15](https://github.com/av/harbor/releases/tag/v0.0.15)

**Comment by av** [comment]
I'm closing since we now have poor man's update, and mentioned one-line installer
