### ISSUE TITLE
How to override default embedding model?

### ISSUE THREAD

**Issue by alsoasnerd** [av/harbor#5]
I want to use other embedding model, but harbor overrides my changes on webui after harbor.sh down && harbor.sh up

**Comment by av** [comment]
Sorry for the inconvenience! We can parameterise it, are you talking about embeddings for the web RAG?

A quick workaround before the parametrisation is available - once you saved your settings in the WebUI, open `open-webui/config.json` and move the settings from there over to `./open-webui/configs/config.override.json`, I'm still thinking how to best handle such cases where a bi-directional configuration flow might be needed

**Comment by alsoasnerd** [comment]
Move my settings to config.override.json doesn't works.

**Comment by alsoasnerd** [comment]
Change config.x.searxng.ollama.json works.

**Comment by av** [comment]
Yes, sorry for the inconvenience again, that's due to the ordering of the configs during merging. The next version will have correct order of precedense, so that overrides are always the last

**Comment by alsoasnerd** [comment]
no problem, thanks for the help

**Comment by av** [comment]
Just pushed the update that fixes ordering of config files when merging, now `config.override.json` will take over all the others, so it should be safe to place changes there

**Comment by av** [comment]
I'm a bit on the fence if
```bash
rag.embedding_engine
rag.embedding_model
```

Should be allowed to be set via `harbor config`, in that instance the users won't be able to adjust them via the Open WebUI later (or the inverse - only UI adjustment works and config doesn't)

**Comment by av** [comment]
[v0.0.15](https://github.com/av/harbor/releases/tag/v0.0.15) has a fix for config precedense, however, the question about bi-directionality remains open

**Comment by av** [comment]
Closing since `.env` now allows for permanent config override
