### ISSUE TITLE
comfyui expects localhost

### ISSUE THREAD

**Issue by lee-b** [av/harbor#50]
Is there a way to set the comfyui host?  I don't see anything in the docs or the .env file for the COMFYUI_HOSTNAME, for example.

If not, then there is an issue, since ComfyUI seems to expect to be served at localhost.  If I connect to it as http://server:34031/ or http://server:34032/, I get redirected to http://localhost:34032/login, which breaks of course, since I'm remote.  The server is headless, of course, so I can't just use that as the client too.

**Comment by av** [comment]
The login screen is provided by the integration called `ai-dock`, its documentation is available here:
https://github.com/ai-dock/comfyui?tab=readme-ov-file#additional-environment-variables

Specifically, it seems that you can specify `COMFYUI_URL` as a full URL including port or `DIRECT_ADDRESS` with the `server` part for this behavior. Note that I didn't test it.

It should be possible to specify these in either root `.env`  or `comfyui/override.env` (available in v0.2.1 release)

**Comment by lee-b** [comment]
Thanks, @av! :)
