### ISSUE TITLE
Unable to start harbor from WSL (Arch)

### ISSUE THREAD

**Issue by cazzoo** [av/harbor#51]
Hi there!
Your project seems really interesting, especially that you provided a way to easily enable LLM or modules (satellites) in a very modular way.
I am running on Windows so I decided to get into WSL (Windows Subsystem Linux) which is a Linux kernel running inside Windows.
I have docker running on my host and available inside my WSL (socket is shared), hosted in my windows host.
```console
❯ docker ps
CONTAINER ID   IMAGE                        COMMAND                  CREATED          STATUS          PORTS     NAMES
e10ee223a4e9   edc812b8e25d                 "entry"                  18 minutes ago   Up 18 minutes             k8s_lb-t
... <truncated>
```

```console
❯ docker version
Client:
 Version:           27.1.1
 API version:       1.45 (downgraded from 1.46)
 Go version:        go1.22.5
 Git commit:        63125853e3
 Built:             Thu Jul 25 17:06:22 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          26.1.5
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.22.5
  Git commit:       411e817ddf710ff8e08fa193da80cb78af708191
  Built:            Fri Jul 26 17:51:06 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.17
  GitCommit:        3a4de459a68952ffb703bbe7f2290861a75b6b67
 runc:
  Version:          1.1.14
  GitCommit:        2c9f5602f0ba3d9da1c2596322dfc4e156844890
 docker-init:
  Version:          0.19.0
  GitCommit:
```

I tried to start harbor, after installing it succesfully, unfortunately, It suddenly stops for a reason I'm unable to diagnose:
```console
❯ ./harbor.sh up
[+] Running 0/2
 ⠋ ollama Pulling                                                                                                  0.1s
 ⠋ webui Pulling                                                                                                   0.1s
error getting credentials - err: exit status 1, out: `Could not connect: No such file or directory`
```

Would you have any idea what's going on?
Any way to move forward?

**Comment by av** [comment]
Thanks for trying out Harbor!

Unfortunately, my own experience with WSL is rather limited and Harbor isn't tested there explicitly (but known to run as per users reports). Hence, I can offer only somewhat generic guidance based on the online research (sorry if these are something you already tried):

Option 1. Docker in WSL2 without `sudo`:
https://stackoverflow.com/q/64710480/15785194
```bash
unset DOCKER_HOST
```
Also
```
 sudo groupadd docker
 sudo usermod -aG docker $USER
 newgrp docker
```

Option 2. Credstore, check Docker Desktop config
https://forums.docker.com/t/error-failed-to-solve-error-getting-credentials-err-exit-status-1-out/136124/2
```json
"credsStore": "desktop",
```

Option 3. D-Bus connection issue, try adding the following lines to your ~/.bashrc file in your WSL environment:
```bash
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"
fi
```

Option 4. D-Bus update
```bash
dbus-update-activation-environment --systemd DISPLAY
```
https://github.com/microsoft/WSL/discussions/9766

**Comment by av** [comment]
Closing, if the above didn't help - please feel free to follow up or open a new issue
