### ISSUE TITLE
Holy Docker Compose💀

### ISSUE THREAD

**Issue by HeavyLvy** [av/harbor#56]
idk what the reason is for all of those compose files to be in the root of the project, 😭 and maybe it was stated somewhere in the docs. But it is lagging the page and looks incredibly messy. Think that should be a sign to put all of that into a folder.👀

**Comment by av** [comment]
It's no scalable, agree! 

I was considering to do this, but it'd require a pretty meticulous and large-scale check of all the paths still matching. Worst case - every single service will have to be re-tested. So I decided to not do that (yet).
