### ISSUE TITLE
How to change default server parameters on ollama?

### ISSUE THREAD

**Issue by alsoasnerd** [av/harbor#6]
Example: I want to set OLLAMA_KEEP_ALIVE permanently, how I can do that?

**Comment by av** [comment]
Just pushed an update (also planned in advance, haha)

Now, `.env` file is no longer tracked by git, so any modifications to it are not conflicting with upstream changes. Previous defaults were moved to `default.env` and are used for the initial population of the `.env`

**Comment by av** [comment]
Also added the `harbor config reset` to bring the `.env` back to current defaults

**Comment by av** [comment]
To your original question, with the latest update, you can specify such global persistent vars in the `.env` in the Harbor workspace without the risk of having a conflict with an update from the upstream.

I've also left a pointer on where ollama vars can go in the `default.env`

**Comment by av** [comment]
released in [v0.0.15](https://github.com/av/harbor/releases/tag/v0.0.15)

**Comment by av** [comment]
Closing as this is now possible after `.env` was detached from the pre-provisioned defaults
