### ISSUE TITLE
Harbor App does not work under Wayland

### ISSUE THREAD

**Issue by maeyounes** [av/harbor#61]
Hello,

great job with the development of this amazing project!

I wanted to try the Harbor App under my Linux system that uses Wayland instead of X11. I get the following error however:
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Cannot get default EGL display: EGL_SUCCESS
Cannot create EGL context: invalid display (last error: EGL_SUCCESS)
```

Even ignoring the error by setting `QT_QPA_PLATFORM=wayland` does not help:
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
Cannot get default EGL display: EGL_SUCCESS
Cannot create EGL context: invalid display (last error: EGL_SUCCESS)
```

**Comment by av** [comment]
Thanks for the kind words and for trying it out!

The `EGL_SUCCESS` should be related to the `webkitgtk` and should be fixed by them in the upcoming releases, meanwhile disabling compositing via env vars could work:
```bash
# Try this first
WEBKIT_DISABLE_DMABUF_RENDERER=1

# If the first doesn't work
WEBKIT_DISABLE_COMPOSITING_MODE=1
```

More info:
https://github.com/tauri-apps/tauri/issues/10749

**Comment by av** [comment]
Sorry for a delayed reply 

This looks like a problem executing `harbor` command, so let's check the very basic things first - is Harbor CLI installed? If not - please see the [installation guide](https://github.com/av/harbor/wiki/1.0.-Installing-Harbor#harbor-cli). 

The next thing to verify would be ensuring that `harbor` is linked and is available globally in $PATH:
```bash
$ which harbor
/home/user/.local/bin/harbor # or similar
```

After that, please try running `harbor doctor` and `harbor info` and post the outputs here.

Thanks!

**Comment by av** [comment]
No worries, thanks for confirming it wasn't some obscure platform bug!

If I'll ever have enough time - there are plans for the app to be self-contained and to manage the CLI installation (not soon, that's for sure though)

**Comment by TGlide** [comment]
I still face this issue. This is the reported error:
```
  󱞪 ./Harbor_0.3.12_amd64.AppImage
Gtk-Message: 18:05:42.408: Failed to load module "colorreload-gtk-module"
Gtk-Message: 18:05:42.408: Failed to load module "appmenu-gtk-module"
Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...
```
