### ISSUE TITLE
`cmdh` installation fails

### ISSUE THREAD

**Issue by PieBru** [av/harbor#66]
Hi,
I just installed `harbor` in a dedicated Arch Linux LXC container on a Proxmox VE standalone server node.
The default apps plus `searxng` and `litellm` installed flawlessy, but `harbor up cmdh` shows an installation error:

![image](https://github.com/user-attachments/assets/941ff821-13c1-4fe0-a7fb-dcad28e5d1f6)

LXC container CPU, RAM and Disk are more than enough.
Did I miss something?

Thank you.
Piero

**Comment by av** [comment]
Thanks for the report, looks like `cmdh` integration went stale, will be fixed in the upcoming release.

Meanwhile - `opint`, `aider`, `aichat` offer similar functionalities, also `fabric` works quite well for the shell-related tasks

**Comment by av** [comment]
Finally got to it!

Should be fixed in [v0.2.15](https://github.com/av/harbor/releases/tag/v0.2.15)

**Comment by av** [comment]
Closing, please feel free to follow up or create a new issue if needed
