### ISSUE TITLE
Suggestion: Open interpreter integration 

### ISSUE THREAD

**Issue by alsoasnerd** [av/harbor#7]
Is this even possible with containers?

**Comment by av** [comment]
Yes, 

I was thinking about integrating it just today. It should be possible with a caveat of a subfolder-only file access down from the $PWD, I need to learn more about it's internals and specifically how the context is constructed, though

**Comment by av** [comment]
Just pushed initial version of the integration, writing some docs now. The (yet) undocumented CLI interface is [here](https://github.com/av/harbor/blob/main/harbor.sh#L1121)

**Comment by av** [comment]
released in [v0.0.17](https://github.com/av/harbor/releases/tag/v0.0.17)

**Comment by av** [comment]
Closing as the integration was made
