### ISSUE TITLE
Integration - Chat Nio

### ISSUE THREAD

**Issue by bhupesh-sf** [av/harbor#74]
Seems quite good options and a nice UI.

[https://github.com/zmh-program/chatnio](https://github.com/zmh-program/chatnio)

**Comment by av** [comment]
Thanks for bringing this to my attention. The service configuration is quite poorly documented, but I think I managed to produce something working.

Will be available in upcoming Harbor release

**Comment by av** [comment]
Released in [v0.2.16](https://github.com/av/harbor/releases/tag/v0.2.16)
