### ISSUE TITLE
Bug: Harbor ollama <parameter>

### ISSUE THREAD

**Issue by alsoasnerd** [av/harbor#8]
OCI runtime exec failed: exec failed: unable to start container process: exec: "ollama list": executable file not found in $PATH: unknown

I removed my host ollama (rm /usr/local/bin/ollama, userdel ollama...). Maybe that caused this issue, idk.

Edit: entering on container and running "ollama list" works, just "harbor ollama list" or "harbor exec ollama "ollama list" doesn't works.

**Comment by av** [comment]
Thank you for reporting! It's a regression after resolving some of the linter messages in the main CLI file - went a tad wrong

Please run `harbor update` and it should be fixed

**Comment by av** [comment]
Closing as config override was fixed
