### ISSUE TITLE
Add ogem

### ISSUE THREAD

**Issue by nullnuller** [av/harbor#84]
Key Features

- One API for Everything: Use OpenAI's API format for all models (GPT-4, Claude, Gemini)
- Smart Routing: Automatic latency-based routing
- Fallback Support: Chain multiple models (gpt-4,claude-3-opus,gemini-1.5-pro)
- Multi-Architecture Docker: Ready for both ARM64 and AMD64

Links
GitHub: [https://github.com/yanolja/ogem](https://github.com/yanolja/ogem)

Docker Hub: [ynext/ogem](https://hub.docker.com/repository/docker/ynext/ogem/general)

Although I haven't tried it, the failover support looks interesting.

**Comment by av** [comment]
Thanks for bringing this in! I also saw the post on r/LocalLLaMa when it was announced. I decided to wait for some time to see if it'll gain any usage, as it overlaps a lot with LiteLLM/OptiLLM

**Comment by av** [comment]
After some time in the oven - it doesn't look like ogem is getting traction or being developed further, so I won't be actively working on this integration. 

With that said, I'm of course open to the contributions in the future and will help in any way I can.
